# https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Asia/Tokyo"
    ignore:
      - dependency-name: "com.android.tools.build:gradle"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
